project:
  type: website
  output-dir: docs

python: ".venv/bin/python"   # <- topo, fora de 'execute'

execute:
  echo: true
  warning: false
  message: false
  cache: false

format:
  html:
    theme: cosmo
    toc: true
