---
title: "Projeto de Machine Learning I"
author: "Bruno Lenz, Danilo Santos, Diogo de Araujo, Jonathan e Osvaldo Jeronymo Neto"
date: today
date-format: long
lang: pt-BR
number-sections: true

# Rotular tabelas como "Quadro" e personalizar Apêndice
crossref:
  tbl-title: "Quadro"      # muda o rótulo na legenda
  tbl-prefix: "Quadro"     # muda o texto nos @tbl-...
  title-delim: " — "
  appendix-title: "Apêndice"
  appendix-delim: " — "

format:
  html:
    toc: true
    theme: cosmo
    tbl-cap-location: top

bibliography: referencias.bib
csl: abnt.csl
---
# Introdução

Este projeto explora a aplicação de técnicas de ***Machine Learning (ML)*** para a análise de dados bancários multimodais, com o objetivo de desenvolver um modelo preditivo para otimizar campanhas de ***cross-sell*** (venda-cruzada). A análise se baseia no ***Multimodal Banking Dataset (MBD)***, um conjunto de dados em larga escala que reflete interações reais de clientes corporativos. 

A metodologia adotada para alcançar esse objetivo abrange um ciclo completo de desenvolvimento de um modelo de *ML*. O processo inicia com a **definição do problema de negócio** e avança para as etapas de **tratamento e transformação dos dados**, que são cruciais dado o caráter multimodal do *dataset*. Subsequentemente, define-se a **métrica de avaliação** mais adequada para o problema de *cross-sell*, seguida pelo desenvolvimento e treinamento de uma solução de *ML* que emprega, no mínimo, três estimadores distintos. Para maximizar a performance, realiza-se a **otimização de hiperparâmetros** desses algoritmos, visando a melhoria da métrica de interesse. O projeto culmina com uma **análise comparativa dos modelos**, resultando na seleção do estimador de melhor desempenho.

A relevância estratégica deste projeto é reforçada por evidências que apontam a maior propensão de clientes existentes em adquirir novos produtos da mesma instituição, uma prática conhecida como cross-selling (@basten2023). Portanto, o trabalho culmina não apenas na entrega de um modelo preditivo validado, mas também em uma análise sobre sua eficácia para a resolução do problema de negócio e um delineamento das etapas essenciais para sua futura implementação em um ambiente de produção.

# Contexto

A primeira etapa do projeto consistiu na seleção de um *dataset* apropiado. A comunidade [***Hugging Face***](https://huggingface.co) foi a fonte escolhida, e dentro da diversidade de *dataset* contidos nessa comunidade optou-se pelo  [Multimodal Banking Dataset - MBD](https://huggingface.co/papers/2409.17587).

Conforme descrito por @mollaev2025, o **MBD** é o primeiro conjunto de dados bancário multimodal, de larga escala e publicamente disponível. Esse *dataset* contém sequências de dados anonimizados de mais de 2 milhões de clientes corporativos de um grande banco. Este dataset inclui **transações financeiras, dados de geolocalização, diálogos de suporte técnico e registros de compras de produtos**. O obetivo da sua criação foi preencher a lacuna de dados abertos no setor financeiro, viabilizando o desenvolvimento de técnicas avançadas de aprendizado profundo. Adicionalmente, os autores propõem um novo **benchmark multimodal** com tarefas práticas como a previsão de futuras compras, que se alinha diretamente com os objetivos desse projeto.

## Problema de negócio

O problema de negócio selecionado é a **predição de propensão à compra em campanhas de *cross-sell* (venda-cruzada)**. Uma campanha de *cross-sell* é uma iniciativa de marketing direcionada a clientes existentes, com o intuito de oferecer produtos complementares aos que já possuem. Por exemplo, oferecer seguro de vida a um cliente que recentemente contratou um financeiro imobiliário. 

O objetivo deste projeto é, portanto, treinar um modelo com o **MBD** para gerar um *score* de propensão para cada cliente. Esse *score* permitirá priorizar os clientes com maior probabilidade de aceitar uma oferta, otimizando os recursos da campanha e aumentando a sua taxa de conversão.

**Delimitação do escopo: cross-sell *vs.* up-sell**

Para garantir a clareza do objetivo, é necessária uma distinção: o escopo deste projeto é estritamente o ***cross-sell***. É importante não confundi-lo com ***up-sell***, que consiste em incentivar o cliente a adquirir uma versão mais avançada ou mais cara de um mesmo produto que ele já possui (ex: migrar de um cartão de crédito "Gold" para um "Platinum"). O modelo aqui desenvolvido focará exclusivamente na oferta de novos e diferentes produtos.

## Repositório

Os artefatos gerados durante o desenvolvimento deste projeto, incluindo notebooks, scripts e relatórios, estão organizados da seguinte forma e podem ser encontrados no seguinte repositório: <https://github.com/osvaldojeronymo/machine-learning-project>.

## Dados

O [**MBD**](https://huggingface.co/datasets/ai-lab/MBD) contém mais de 2 milhões de dados de clientes corporativos. Nesse projeto optou-se por trabalhar com [***MBD-mini dataset***](https://huggingface.co/datasets/ai-lab/MBD-mini), que contém um subconjunto reduzido dos dados, essa estratégia facilitará os trabalhos de desenvolvimento e teste do modelo proposto. Esse ***MBD-mini dataset*** têm dados baseados em 10% de clientes únicos listados no **MBD**. Como apresentado por @mollaev2025 no @tbl-overview, têm-se:

: Visão geral de conjuntos de dados de transações existentes {#tbl-overview}

| Conjunto de dados         | Nº de clientes | Tarefas-alvo (*downstream*)                             | Nº de eventos | Balanço de classes       | Modalidades                                 |
|---------------------------|---------------:|---------------------------------------------------------|--------------:|--------------------------|---------------------------------------------|
| DataFusion                |        22 mil  | Classificação binária; *matching* multimodal            |   146 milhões | Desbalanceado            | Transações; Clickstream                     |
| Alphabattle               |     1,5 milhão | Classificação binária                                   |   443 milhões | Desbalanceado            | Transações                                  |
| Age                       |        50 mil  | Classificação multiclasse                               |    44 milhões | Balanceado               | Transações                                  |
| Rosbank                   |        10 mil  | Classificação binária                                   |     1 milhão  | Desbalanceado            | Transações                                  |
| Credit Card Transaction   |         2 mil  | Classificação binária; Regressão                        |     2 milhões | Altamente desbalanceado  | Transações                                  |
| MBD-small (nosso)         |        70 mil  | Classificação binária multirrótulo; *matching* multimodal |    80 milhões | Desbalanceado            | Transações; Geostream (eventos geográficos); Diálogos |
| MBD (nosso)               |      2 milhões | Classificação binária multirrótulo; *matching* multimodal |     2 bilhões | Altamente desbalanceado  | Transações; Geostream (eventos geográficos); Diálogos |

**Fonte:** @mollaev2025. DOI: 10.48550/arXiv.2409.17587. *Tradução nossa.*
